### ISSUE TITLE
Usage instructions outdated?

### ISSUE THREAD

**Issue by mikerofone** [anothertobi/viseca-exporter#17]
Hi,

thanks for creating this handy tool! I found that the instructions in the README gave me an error, but I found a workaround using a different `main.go`. Maybe the instructions need an update?

What I ran:

```
$  export VISECA_CLI_USERNAME=<my-email>
$  export VISECA_CLI_PASSWORD=<my-password>
$  export VISECA_CARD=<my-card-ID>
$ go run cmd/viseca-cli/main.go transactions ${VISECA_CARD}
2023/09/07 00:09:30 context deadline exceeded
exit status 1
```

I noticed the recently-changed `main.go` in the root of the repo, and gave that a shot:

```
$  export VISECA_SESS=<my AL_SESS-S cookie copied from Chrome cookie jar>
$  export VISECA_CARD=<my card ID>
$ go run main.go ${VISECA_CARD}  ${VISECA_SESS} 
"TransactionID","Date","Merchant","Amount","PFMCategoryID","PFMCategoryName"
<list of the last 2 years of transactions>
```

So my 2 rappen say that the instructions would better point to the newer `main.go` using the session cookie.

Thanks again!
Cheers
mikerofone

**Comment by anothertobi** [comment]
The simple method in `cmd/viseca-cli/main.go` is based on a reverse engineered web auth flow. This auth flow seems to have slightly changed and now leads to errors (app-confirmation just redirects to the login page instead of authenticating the session).

Extracting the `AL_SESS-S` cookie from an authenticated browser is the fallback method, which luckily still works.
